kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-boot-3-and-rest-template
  namespace: edwin-ns
  labels:
    app: spring-boot-3-and-rest-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-3-and-rest-template
  template:
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: ENDPOINT
              value: 'https://jsonplaceholder.typicode.com/posts/5'
          terminationMessagePath: /dev/termination-log
          name: spring-boot-3-and-rest-template
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/edwin-ns/spring-boot-3-and-rest-template:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600